version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  api:
    build: .
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db
