version: '3.1'

services:
  db:
    container_name: postgres
    image: postgres:latest
    env_file: database.conf
    ports:
      - 5432:5432  

  api:
    build: .
    restart: always
    env_file: database.conf
    ports:
      - 5000:5000
    depends_on:
      - db
