openapi: 3.0.0
info:
  version: 1.0.0
  title: User Service API

paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Registered successfully
        '400':
          description: Bad Request

  /update:
    put:
      summary: Update user information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                name:
                  type: string
                surname:
                  type: string
                birth_date:
                  type: string
                email:
                  type: string
                phone:
                  type: string
      responses:
        '200':
          description: Data updated
        '400':
          description: Bad Request or User not found

  /login:
    post:
      summary: Log in
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Logged in
        '400':
          description: Wrong username or password
